# goal sent to client
string action_name
---
# result sent to server
string grasp_state
---
# feedback sent to server
geometry_msgs/PoseStamped[] grasp_candidates
float64[] costs
uint32 num_candidates
